### ISSUE TITLE
Is there a render function like gym?

### ISSUE THREAD

**Issue by BBDrive** [dosssman/GymTorcs#1]

**Comment by dosssman** [comment]
Yes.

You can enable rendering by passing `rendering=True` to gym.make().
Not recommended during training though, as it might slow down the process quite considerably.

Also, I would not recommend using this wrapper if you need image observation, at least not yet.
The support is good enough.

**Comment by BBDrive** [comment]
Thank you! This is a great project!
However, when i run `o ,r, done = env.reset(), 0., False`, this happen in the window.

>>> o,r,done=env.reset(),0.,False
Waiting for server on 3000............
Count Down : 5
Waiting for server on 3000............
Count Down : 4
Waiting for server on 3000............
Count Down : 3
Waiting for server on 3000............
Count Down : 2
Waiting for server on 3000............
Count Down : 1
Waiting for server on 3000............
Count Down : 0
Waiting for server on 3000............
Count Down : -1

Fuel consumption disabled!
Laptime limit disabled!
Speed set to 1x realtime!
UDP Listen Port set to 3000!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Waiting for server on 3000............
Count Down : 4
Waiting for server on 3000............
Count Down : 3
Waiting for server on 3000............
Count Down : 2
Waiting for server on 3000............
Count Down : 1
Waiting for server on 3000............
Count Down : 0
Waiting for server on 3000............
Count Down : -1

And the image window keeps generating. How can I do？

**Comment by dosssman** [comment]
Just to be sure, have you installed the binaries via the `deps_install_script.sh` ?

This message hints that the wrapper is not able to connect to the simulator itself.
Also, what distribution are you running it on ?
And could you please elaborate on what you mean by "And the image window keeps generating." ?

**Comment by BBDrive** [comment]
Sorry，i forgot to install the binaries. 
It's ok now. I will read your code carefully so that i can use it. 
Thank you for your help.

**Comment by dosssman** [comment]
Great!
Could you please let me know if you had any trouble with the script ?
As well as which distribution of Linux you used to run it ?

I shall use it to update the script if needed, as well as the README so it is easier to understand.

**Comment by BBDrive** [comment]
OK. i will contact you if i have any problem. 
I run it on Ubuntu 16.

**Comment by dosssman** [comment]
Thanks for the feedback.

**Comment by BBDrive** [comment]
Hello, I have some questions about the code.
1.Why the dimension of the image is 1 instead of (64,64,3)?
2.How to select a track randomly?
3.What does the parameter ‘race_speed’ mean?
4.I am not sure what is the use of recording data and can I extract data from it?
Thanks.

**Comment by dosssman** [comment]
Greetings.

1. -> Just to make sure, but are you passing `vision=True` to the `gym.make(...)` command ? If so, the image data might be flattened, hence dim = 1. I shall check the expected output if I have some time later.

2. -> Unfortunately, there is not such feature yet. What is supported is randomizing the number and position of bots on the track.

3. -> race_speed is there to control the speed of the simulation. The higher the value, the faster the simulation, up to the computation limits of the machine.

4. -> recording_data is used to dump the observations as well as the actions the agent / human player takes. I needed it for a specific experiment, but you probably do not need to use it.

Hope it helps somehow.

**Comment by BBDrive** [comment]
If I want to extract data from record_data, how should i do?

**Comment by dosssman** [comment]
First, the path where the data is saved to the path described by the environment variable `TORCS_DATA_DIR`, so you will need to set it to an existing folder on the machine where you want the data to be dumped to.
Something in the lines of `export TORCS_DATA_DIR=/home/<username>/torcs_data` added to the ~/.bashrc file should do the trick.

The data is saved in the CSV format as per https://github.com/dosssman/gym_torqs/blob/dd7426bee5a62281b263e4e1d9b36e7721ce61e5/vtorcs-RL-color/src/libs/raceengineclient/racestate.cpp#L413.

It saves the observations to a file named obs.csv, actions to acs.csv (?) and rewards to rews.csv.
The data of one episode is saved on a single line, so there is a need to know the dimension of the observation / actions to recover it as proper transitions (see script below).
Please keep in mind that the format the observations are encoded in is hard coded, so it might need some tweaking of the libraries and recompiling for it to work as intended.

Once the data is collected, I would use the following csv2npy.py script to load it as numpy arrays 

and to the various processing there.
[csv2npy.zip](https://github.com/dosssman/GymTorcs/files/4681555/csv2npy.zip)

**Comment by dosssman** [comment]
Also, the image support is really messy, and I did not use it for my experiments ...

**Comment by BBDrive** [comment]
Great! Thank you very much.

**Comment by BBDrive** [comment]
If I set `rendering = False`, it still create a window without anything, does it?

**Comment by dosssman** [comment]
Indeed. The best work around I could find was to use `xvfb` so the window is created in a virtual display.

Please try running your code with `xvfb-run -a python training.py` for example.

**Comment by dosssman** [comment]
I would usually run it with
`xvfb-run -a -s "-screen $DISPLAY 640x480x24" python train.py`, with DISPLAY=:0

**Comment by BBDrive** [comment]
So we still can't prevent the window from creating, right?

**Comment by dosssman** [comment]
Yes, there will always be a window.

**Comment by BBDrive** [comment]
Compared with having GUI, will it improve in speed?

**Comment by dosssman** [comment]
When passing rendering = False, the simulation will be faster, since there will be no rendering (just a black window basically).
It gets even faster when using xvfb for some reason.

As far as I remember, however, rendering needs to be enabled in case you want to use pixel observations...

**Comment by BBDrive** [comment]
Nice!

**Comment by BBDrive** [comment]
Hi.
You forgot to add the file "agent_randfixed_tmplt.xml".

**Comment by dosssman** [comment]
Thanks for the heads up.
Added in the latest commit to the master branch.

**Comment by BBDrive** [comment]
Hello.
How should i do if i want to play the 'torcs' by myself and record the data?

**Comment by dosssman** [comment]
Greetings.

You can record your own gameplay by running the Torcs Binary directly, while providing the race configuration file, such as:
```
torcs -raceconfig $PWD/human_10fixed_sparse_2.xml -rechum 0 -rectimesteplim 3600
``` 
for example.

A sample of the race config XML file in case you are playing as a human (you can remove / add the bots if not needed is provided below.
Beside that, the `-rechum` parameter indicates the index of the human player which data will be recorded.
The recorded data goes into the `$USER/torcs_data`, so you might want to create it before hand.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE params SYSTEM "params.dtd">


<params name="Practice">
  <section name="Header">
    <attstr name="name" val="Practice"/>
    <attstr name="description" val="Practice"/>
    <attnum name="priority" val="100"/>
    <attstr name="menu image" val="data/img/splash-practice.png"/>
    <attstr name="run image" val="data/img/splash-run-practice.png"/>
  </section>

  <section name="Tracks">
    <attnum name="maximum number" val="1"/>
    <section name="1">
      <attstr name="name" val="g-track-1"/>
      <attstr name="category" val="road"/>
    </section>

  </section>

  <section name="Races">
    <section name="1">
      <attstr name="name" val="Practice"/>
    </section>

  </section>

  <section name="Practice">
    <attnum name="laps" val="1"/>
    <attstr name="type" val="practice"/>
    <attstr name="starting order" val="drivers list"/>
    <attstr name="restart" val="yes"/>
    <attstr name="display mode" val="normal"/>
    <attstr name="display results" val="yes"/>
    <attnum name="distance" unit="km" val="0"/>
    <section name="Starting Grid">
      <attnum name="rows" val="1"/>
      <attnum name="distance to start" val="200"/>
      <attnum name="distance between columns" val="20"/>
      <attnum name="offset within a column" val="10"/>
      <attnum name="initial speed" unit="km/h" val="0"/>
      <attnum name="initial height" unit="m" val="0.2"/>
    </section>

  </section>

  <section name="Drivers">
    <attnum name="maximum number" val="11"/>
    <attstr name="focused module" val="human"/>
    <attnum name="focused idx" val="1"/>
    <section name="1">
      <attnum name="idx" val="1"/>
      <attstr name="module" val="human"/>
    </section>
    <section name="2">
      <attnum name="idx" val="0"/>
      <attstr name="module" val="fixed"/>
    </section>
    <section name="3">
      <attnum name="idx" val="1"/>
      <attstr name="module" val="fixed"/>
    </section>
    <section name="4">
      <attnum name="idx" val="2"/>
      <attstr name="module" val="fixed"/>
    </section>
    <section name="5">
      <attnum name="idx" val="3"/>
      <attstr name="module" val="fixed"/>
    </section>
    <section name="6">
      <attnum name="idx" val="4"/>
      <attstr name="module" val="fixed"/>
    </section>
    <section name="7">
      <attnum name="idx" val="5"/>
      <attstr name="module" val="fixed"/>
    </section>
    <section name="8">
      <attnum name="idx" val="6"/>
      <attstr name="module" val="fixed"/>
    </section>
    <section name="9">
      <attnum name="idx" val="7"/>
      <attstr name="module" val="fixed"/>
    </section>
    <section name="10">
      <attnum name="idx" val="8"/>
      <attstr name="module" val="fixed"/>
    </section>
    <section name="11">
      <attnum name="idx" val="9"/>
      <attstr name="module" val="fixed"/>
    </section>

    <!-- Initdist for first driver-->

    <!-- Initdist for first driver-->
    <attnum name="initdist_1" val="200"/>
    <attnum name="initdist_2" val="300"/>
    <attnum name="initdist_3" val="400"/>
    <attnum name="initdist_4" val="500"/>
    <attnum name="initdist_5" val="600"/>
    <attnum name="initdist_6" val="700"/>
    <attnum name="initdist_7" val="800"/>
    <attnum name="initdist_8" val="850"/>
    <attnum name="initdist_9" val="900"/>
    <attnum name="initdist_10" val="1000"/>
    <attnum name="initdist_11" val="1150"/>

  </section>

  <section name="Configuration">
    <attnum name="current configuration" val="4"/>
    <section name="1">
      <attstr name="type" val="track select"/>
    </section>

    <section name="2">
      <attstr name="type" val="drivers select"/>
    </section>

    <section name="3">
      <attstr name="type" val="race config"/>
      <attstr name="race" val="Practice"/>
      <section name="Options">
        <section name="1">
          <attstr name="type" val="race length"/>
        </section>

        <section name="2">
          <attstr name="type" val="display mode"/>
        </section>

      </section>

   </section>
  </section>

</params>
```

**Comment by BBDrive** [comment]
Does the xml file have parameter descriptions? I don’t understand some parameters in xml file.

**Comment by dosssman** [comment]
**(EDIT: Misread your question, wrong response)**
The lengthy code block my previous comment is the content of the `$PWD/human_10fixed_sparse_2.xml` that is passed in the `torcs -raceconfig $PWD/human_10fixed_sparse_2.xml -rechum 0 -rectimesteplim 3600` command.

So you would just need to copy that block into an XML your create on your own machine, then pass the name of that file when running the command.

Additionally, `-rectimesteplim 3600` makes the binary record only 3600 time steps and stop the game after that. Please adjust to your need.

**Comment by dosssman** [comment]
My bad, I misread your question.
Here is a beginning of the correct answer: http://xed.ch/help/torcs.html

Had to figure out the rest manually.
The most important sections should be the "Drivers" and "Track" one, the rest does not matter that much.

**Comment by BBDrive** [comment]
Wow. That's nice.
Let's me try. 
Thank you for your answer.

**Comment by dosssman** [comment]
No problem. Glad to be of some help.
